;---- Text Style for Settings ----

[SettingsStyle-Title]
	StringAlign=Left
	StringStyle=Normal
	InlineSetting=Face | Calibri
	InlineSetting2=Color | 0,0,0
	InlineSetting3=Weight | 700
	InlineSetting4=Size | 9
	AntiAlias=1
	X=5
	Y=5

[SettingsStyle-Text]
	StringAlign=Left
	StringStyle=Normal
	InlineSetting=Face | Calibri
	InlineSetting2=Weight | 500
	InlineSetting3=Size | 9
	FontColor=210,210,210
	AntiAlias=1
	X=15
	DynamicVariables=1

[SettingsStyle-Text2]
	StringAlign=Left
	StringStyle=Normal
	InlineSetting=Face | Calibri
	InlineSetting2=Weight | 700
	InlineSetting3=Size | 12
	FontColor=210,210,210
	AntiAlias=1
	X=15
	DynamicVariables=1

[SettingsStyle-ButtonText]
	StringAlign=Center
	StringStyle=Normal
	InlineSetting=Face | Calibri
	InlineSetting2=Color | 40,40,40
	InlineSetting3=Weight | 500
	InlineSetting4=Size | 9
	AntiAlias=1
	Y=6r

[SettingsStyle-Input]
	StringAlign=Left
	StringStyle=Normal
	InlineSetting=Face | Calibri
	InlineSetting2=Color | 230,230,230
	InlineSetting3=Weight | 500
	InlineSetting4=Size | 8
	AntiAlias=1
	Clipstring=1
	DynamicVariables=1

[SettingsStyle-PanelBG]
	AntiAlias=1
	X=25r
	Y=0r
	W=20
	H=20

[SettingsStyle-CircleBG]
	AntiAlias=1
	X=20r
	Y=0r
	W=15
	H=15

[SettingsStyle-CircleRL]
	AntiAlias=1
	X=25r
	Y=0r
	W=20
	H=20

