[Variables]
;---- Revision ----
SYSMonitorRev=1.5

Skin01			=CPU
Skin01Support	=Windows, HWiNFO1, HWiNFO2, MSIAB

Skin02			=CPU2
Skin02Support	=HWiNFO1, HWiNFO2

Skin03			=ProcView
Skin03Support	=Windows

Skin04			=ProcView2
Skin04Support	=Windows

Skin05			=GPU
Skin05Support	=Windows, HWiNFO1, HWiNFO2, MSIAB

Skin06			=GPU2
Skin06Support	=HWiNFO1, HWiNFO2, MSIAB

Skin07			=FPSView
Skin07Support	=HWiNFO1, MSIAB

Skin08			=RAM
Skin08Support	=Windows, HWiNFO1, HWiNFO2

Skin09			=Mainboard
Skin09Support	=HWiNFO1

Skin10			=Liquid
Skin10Support	=HWiNFO1

Skin11			=WiFi
Skin11Support	=Windows

Skin12			=Network
Skin12Support	=Windows

Skin13			=Network2
Skin13Support	=Windows

Skin14			=FritzBox
Skin14Support	=Windows

Skin15			=DualDrive
Skin15Support	=Windows, HWiNFO1, HWiNFO2

Skin16			=DualDrive2
Skin16Support	=Windows, HWiNFO1, HWiNFO2

Skin17			=Drive1
Skin17Support	=Windows, HWiNFO1, HWiNFO2

Skin18			=Drive2
Skin18Support	=Windows, HWiNFO1, HWiNFO2

Skin19			=Drive3
Skin19Support	=Windows, HWiNFO1, HWiNFO2

Skin20			=Drive4
Skin20Support	=Windows, HWiNFO1, HWiNFO2

Skin21			=Drive5
Skin21Support	=Windows, HWiNFO1, HWiNFO2

Skin22			=Drive6
Skin22Support	=Windows, HWiNFO1, HWiNFO2

Skin23			=Drive7
Skin23Support	=Windows, HWiNFO1, HWiNFO2

Skin24			=Drive8
Skin24Support	=Windows, HWiNFO1, HWiNFO2

Skin25			=Power
Skin25Support	=Windows

Skin26			=Trash
Skin26Support	=Windows

Skin27			=Time
Skin27Support	=Windows

Skin28			=Webradio
Skin28Support	=Windows

Skin29			=Volume
Skin29Support	=Windows
