[variables]

;Unicodes
;ä [\x00E4]
;ö [\x00F6]
;ü [\x00FC]
;ß [\x00DF]

;--- General Variables ---

VarActivateWindowsSkins	=Aktiviere Windows Skins f[\x00FC]r Gruppe
VarActivateHWiNFO1Skins	=Aktiviere HWiNFO 1 Skins f[\x00FC]r Gruppe
VarActivateHWiNFO2Skins	=Aktiviere HWiNFO 2 Skins f[\x00FC]r Gruppe
VarActivateMSIABSkins	=Aktiviere MSIAB Skins f[\x00FC]r Gruppe
VarAVGFPS				=Min/Avg/Max FPS
VarBack					=Zur[\x00FC]ck
VarBackgroundColor		=Hintergrundfarbe
VarBackgroundSetting	=Hintergrund Einstellungen
VarBackgroundShadow		=Hintergrundschatten
VarBarColor				=Balkenfarbe
VarBat0					=Kein Akku
VarBat1					=Wird geladen
VarBat2					=Kritisch
VarBat3					=Niedrig
VarBat4					=Gut
VarBig					=Gro[\x00DF]
VarButtonColor			=Schaltfl[\x00E4]chen
VarCalendar				=Big Panel Kalender
VarCapitalLetter		=Nur Gro[\x00DF]buchstabe des#CRLF#Laufwerks angeben
VarClose				=Schlie[\x00DF]en
VarColor				=Farbe
VarColored				=Farbiges Logo
VarColoredFrame			=Farbiger Rahmen
VarColoredSpeaker		=Farbiger Lautsprecher
VarCWIsoFormat			=ISO8601 Woche
VarDivider				=Skala
VarDown					=Unten
VarDriveLetter			=Laufwerk
VarDriveSSDHDD			=SSD Logo statt HDD
VarDualColor			=Zweifarbig
VarDualDriveSelection	=Alle individuellen Einstellungen werden vom jeweiligen Laufwerk [\x00FC]bernommen
VarFBLED				=Fritz!Box Status LED
VarFBMisc				=Sonstiges
VarFBRequirements		=Fritz!Box Voraussetzungen
VarFBRefresh			=Fritz!Box Automatische Aktualisierung
VarFiles				=Dateien
VarFontColor			=Schriftfarbe
VarFPSDisplayRes		=HWiNFO Aufl[\x00F6]sung
VarFrame				=Panel Rahmen
VarFRMTimes				=MSIAB Frametime
VarFree					=frei
VarGlossyEffect			=Glossy 3D Effekt
VarHelp					=Hilfe
VarHelpMail				=Kontakt
VarHelpWeb				=[\x00F6]ffne Web
VarHideBatStatus		=Zeige Akku Status
VarHideBIOS				=BIOS Version ausblenden
VarHideOutput			=Zeige aktiven Anschlu[\x00DF]
VarHideSensor1			=Sensor1 ausblenden
VarHideVol				=Zeige Lautst[\x00E4]rke
VarHideWiFiQuality		=Zeige WLAN Qualit[\x00E4]t
VarHideWiFiSSID			=Zeige SSID
VarHWiNFOConfig			=Allgemeine Hinweise
VarImage				=Logo
VarIcons				=Farbige Icons
VarImportColorSettings	=Alle Farbeinstellungen von Circles [\x00FC]bernehmen
VarImportColorSettings2	=Alle Farbeinstellungen von Panels [\x00FC]bernehmen
VarLanguage				=Spracheinstellungen
VarLanguage2			=Sprache
VarLastCall				=Letzter Anruf
VarLeadingZeroes		=F[\x00FC]hrende 0
VarLeftRL				=linker Tacho
VarLifetime				=verbleiben
VarLiquidInfo			=- Linker Tacho zeigt Tempteratursensor.#CRLF#- Rechter Tacho zeigt Summe aller 3 L[\x00FC]fter. #CRLF#- Bei weniger als 3 L[\x00FC]fter am Radiator einfach doppelt eintragen.
VarMainboardInfo		=- Erste Zeile zeigt Chipsatz (links) und Sensor1 (rechts) Temperatur.#CRLF#- Zweite Zeile zeigt Mainboard Temp (links) und BIOS Version.#CRLF#- Bei weniger als 4 L[\x00FC]fter im System einfach doppelt eintragen.
VarManual				=Handbuch
VarManual2				=[\x00F6]ffne PDF
VarMaxFPSCount			=Max FPS
VarMid					=Mitte
VarMouseFunctions		=Mausfunktionen
VarOptions				=Allgemeine Optionen
VarPanelBarBG			=Balkenhintergrund
VarPanelFrameShadow		=Panel Rahmenschatten
VarPanelSize			=Panel Format
VarPower				=Batterie
VarPrimaryDisplay		=Prim[\x00E4]rer Monitor
VarRequirements			=Voraussetzungen
VarRightRL				=rechter Tacho
VarRMDescritption		=Empfohlene Einstellungen in Rainmeter:#CRLF#- Hardwarebeschleunigung aktivieren
VarRoundline			=Tachofarbe
VarRoundlineName		=Tacho
VarRoundlineShadow		=Tacho-Schatten
VarSelectDisk			=W[\x00E4]hle Laufwerke
VarSettings				=Konfiguration
VarSettingsColor		=Farbeinstellungen
VarSettingsEdit			=Konfiguration direkt modifizieren
VarSettingsEditVar		=Allgemeine Opt.
VarSettingsEditWin		=Windows Optionen
VarSettingsEditHWiNFO	=HWiNFO Optionen
VarSettingsEditMSIAB	=MSI AB Optionen
VarSettingsEditRadio	=Radiosender
VarSettingsGeneral		=Allgemeine Einstellungen
VarSettingsMouseScale	=Mausskalierung
VarSettingsSkins		=Skin Einstellungen
VarSettingsTemperature	=Temperatureinheit
VarSettingsUtilities	=Hardware[\x00FC]berwachung
VarShadowColor			=Schattenfarbe
VarShowAllFans			=Summe aller 4 L[\x00FC]fter in rechtem Tacho aktivieren. Bitte nur Min/Max Werte oben anpassen (Summe aller Fans).
VarShowDriveUsageLeft	=Zeige Speicherauslastung in linkem Tacho statt HWiNFO Sensor
VarShowDriveUsageRight	=Zeige Speicherauslastung in rechtem Tacho statt HWiNFO Sensor
VarShowFreeSpace		=Zeige freien Speicher
VarShowPercent			=Zeige % Werte
VarShowRamOnly			=Zeige Swap in Tacho
VarShowRamTemp			=Zeige Temp in Tacho
VarShowSeconds			=Zeige Sekunden
VarShowTitle			=Zeige Skin Titel
VarShowVolume			=Zeige Lautst[\x00E4]rke
VarSingleColor			=Einfach
VarSmall				=Klein
VarSquare				=Quadratisch
VarStartOnMonday		=Start mit Montag
VarStationImageHelp		=Erstelle ein Bild deines bevorzugten Senders und speichere dieses im 'Stations' Verzeichnis. Das Bild sollte mind. 100x100px gro[\x00DF] sein, ggf. mit transparentem Hintergrund.
VarStationImages		=Senderlogos
VarStreamConfig			=Stream Konfiguration
VarStreamConfigHelp		=W[\x00E4]hle Sender 1 - 8. Trage nun in die Felder den Sendernamen, den Dateinamen des Logos (ohne Pfad) und den direkten Stream Link ein. Optional kann noch ein Link zur online Songliste hinterlegt werden. 
VarSysMonRequirements	=- OS: Windows 10, 64bit, v1809 oder neuer#CRLF#- Generell: Rainmeter v4.3.1 oder neuer installiert#CRLF#- HWiNFO Skins: HWiNFO Utility installiert und aktiv#CRLF#- MSIAB Skins: MSI Afterburner Utility installiert und aktiv#CRLF#- Webradio: VLC Mediaplayer installiert
VarTechnology			=Technologie
VarTimeFormat			=Zeitformat
VarToggle				=Skins Ein/Aus
VarTotal				=Gesamt
VarTripleColor			=Dreifarbig
VarUp					=Oben
VarUsed					=belegt
VarVLCHelp				=Das Abspielen der Streams basiert auf VLC Media Player. Setze nach der Installation von VLC den Pfad zur vlc.exe in den Einstellungen.
VarVLCPath				=Vollst[\x00E4]ndiger Pfad zu VLC Media Player


;--- Time Variables ---

TIWeek					=KW
TIWD0					=So
TIWD1					=Mo
TIWD2					=Di
TIWD3					=Mi
TIWD4					=Do
TIWD5					=Fr
TIWD6					=Sa

TIMonth1				=Januar
TIMonth2				=Februar
TIMonth3				=Maerz
TIMonth4				=April
TIMonth5				=Mai
TIMonth6				=Juni
TIMonth7				=Juli
TIMonth8				=August
TIMonth9				=September
TIMonth10				=Oktober
TIMonth11				=November
TIMonth12				=Dezember

;--- Trash Variables ---
VarTrash				=Papierkorb
VarVolume				=Lautst[\x00E4]rke