////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
VARIABLES

[Variables]
Language=English

List of Language:
Français=French
English=English
Español=Spanish

----------------------------------

Player=AIMP

List of player:
AIMP=aimp
foobar2000 - VLC - MusicBee - J. River Media Center Media Jukebox=CAD 
iTunes=iTunes
Winamp=Winamp
Windows Media Player=WMP
MediaMonkey=MediaMonkey
Spotify=Spotify
