[variables]

PathToVLC				=C:\Program Files\VideoLAN\VLC\vlc.exe

StationTitle1			=Technobase.FM
StationImage1			=TechnobaseFM.png
StationURL1				=http://listen.technobase.fm/aac-hd.pls
StationTrackListURL1	=https://www.technobase.fm/tracklist

StationTitle2			=Hardbase.FM
StationImage2			=HardbaseFM.png
StationURL2				=http://listen.hardbase.fm/aac-hd.pls
StationTrackListURL2	=https://www.hardbase.fm/tracklist

StationTitle3			=Trancebase.FM
StationImage3			=TrancebaseFM.png
StationURL3				=http://listen.trancebase.fm/aac-hd.pls
StationTrackListURL3	=https://www.trancebase.fm/tracklist/

StationTitle4			=Coretime.FM
StationImage4			=CoretimeFM.png
StationURL4				=http://listen.coretime.fm/aac-hd.pls
StationTrackListURL4	=https://www.coretime.fm/tracklist/

StationTitle5			=Teatime.FM
StationImage5			=TeatimeFM.png
StationURL5				=http://listen.teatime.fm/aacplus.pls
StationTrackListURL5	=https://www.teatime.fm/tracklist/

StationTitle6			=Clubtime.FM
StationImage6			=ClubtimeFM.png
StationURL6				=http://listen.clubtime.fm/aac-hd.pls
StationTrackListURL6	=https://www.clubtime.fm/tracklist/

StationTitle7			=Housetime.FM
StationImage7			=HousetimeFM.png
StationURL7				=http://listen.housetime.fm/aac-hd.pls
StationTrackListURL7	=https://www.housetime.fm/tracklist/

StationTitle8			=Replay.FM
StationImage8			=ReplayFM.png
StationURL8				=http://listen.replay.fm/aac-hd.pls
StationTrackListURL8	=https://www.replay.fm/trackliste


