[variables]

PathToVLC				=C:\Program Files\VideoLAN\VLC\vlc.exe

StationTitle1			=Technobase.FM
StationImage1			=TechnobaseFM.png
StationURL1				=http://listen.technobase.fm/aac-hd.pls
StationTrackListURL1	=https://www.technobase.fm/tracklist

StationTitle2			=Hardbase.FM
StationImage2			=HardbaseFM.png
StationURL2				=http://listen.hardbase.fm/aac-hd.pls
StationTrackListURL2	=https://www.hardbase.fm/tracklist

StationTitle3			=Teatime.FM
StationImage3			=TeatimeFM.png
StationURL3				=http://listen.teatime.fm/aacplus.pls
StationTrackListURL3	=https://www.teatime.fm/tracklist/

StationTitle4			=bigFM EDM
StationImage4			=bigFM.png
StationURL4				=http://streams.bigfm.de/bigfm-nitroxedm-128-aac?usid=0-0-H-A-D-30
StationTrackListURL4	=https://www.bigfm.de/playlist

StationTitle5			=Antenne Top40
StationImage5			=AntenneTop40.png
StationURL5				=http://www.antenne.de/webradio/channels/top-40.m3u
StationTrackListURL5	=http://www.webradio.de/antenne-bayern/top-40

StationTitle6			=bigFM Charts
StationImage6			=bigFM.png
StationURL6				=http://streams.bigfm.de/bigfm-charts-128-aac?usid=0-0-H-A-D-30
StationTrackListURL6	=https://www.bigfm.de/playlist

StationTitle7			=Antenne Hitmix
StationImage7			=AntenneHitmix.png
StationURL7				=http://www.antenne.de/webradio/channels/hitmix.m3u
StationTrackListURL7	=https://www.webradio.de/antenne-bayern/hitmix

StationTitle8			=Antenne Fresh
StationImage8			=AntenneFresh.png
StationURL8				=http://www.antenne.de/webradio/channels/fresh.m3u
StationTrackListURL8	=https://www.webradio.de/antenne-bayern/fresh4you
