[variables]

PathToVLC				=C:\Program Files\VideoLAN\VLC\vlc.exe

StationTitle1			=UnserRadio
StationImage1			=UnserRadio.png
StationURL1				=http://rs4.stream24.net:80/unser-radio.mp3
StationTrackListURL1	=https://onlineradiobox.com/de/unserradio/playlist/

StationTitle2			=Bayern 1
StationImage2			=Bayern1.png
StationURL2				=https://streams.br.de/bayern1nbopf_2.m3u
StationTrackListURL2	=https://www.br.de/radio/bayern-1/welle110.html

StationTitle3			=Bayern 3
StationImage3			=Bayern3.png
StationURL3				=http://br-br3-live.cast.addradio.de/br/br3/live/mp3/128/stream.mp3
StationTrackListURL3	=http://www.br.de/radio/bayern-3/bayern-3-playlist-musiktitel-recherche/index.html

StationTitle4			=Antenne Oldies
StationImage4			=AntenneOldies.png
StationURL4				=http://www.antenne.de/webradio/channels/oldies-but-goldies.m3u
StationTrackListURL4	=https://www.webradio.de/antenne-bayern/oldies-but-goldies

StationTitle5			=Antenne Hitmix
StationImage5			=AntenneHitmix.png
StationURL5				=http://www.antenne.de/webradio/channels/hitmix.m3u
StationTrackListURL5	=https://www.webradio.de/antenne-bayern/hitmix

StationTitle6			=Antenne Fresh
StationImage6			=AntenneFresh.png
StationURL6				=http://www.antenne.de/webradio/channels/fresh.m3u
StationTrackListURL6	=https://www.webradio.de/antenne-bayern/fresh4you

StationTitle7			=Antenne Top40
StationImage7			=AntenneTop40.png
StationURL7				=http://www.antenne.de/webradio/channels/top-40.m3u
StationTrackListURL7	=http://www.webradio.de/antenne-bayern/top-40

StationTitle8			=Rock Antenne
StationImage8			=RockAntenne.png
StationURL8				=http://mp3channels.webradio.antenne.de:80/rockantenne
StationTrackListURL8	=http://www.webradio.de/antenne-bayern/rock-antenne



