[variables]

PathToVLC				=C:\Program Files\VideoLAN\VLC\vlc.exe

StationTitle1			=1Live
StationImage1			=1Live.png
StationURL1				=https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3
StationTrackListURL1	=https://www1.wdr.de/radio/1live/on-air/1live-playlist/index.html

StationTitle2			=SWR3
StationImage2			=SWR3.png
StationURL2				=https://swr-swr3-live.cast.addradio.de/swr/swr3/live/mp3/128/stream.mp3
StationTrackListURL2	=https://www.swr3.de/playlisten/index.html

StationTitle3			=bigFM Deutschland
StationImage3			=bigFM.png
StationURL3				=http://streams.bigfm.de/bigfm-deutschland-128-aac?usid=0-0-H-A-D-30
StationTrackListURL3	=https://www.bigfm.de/playlist

StationTitle4			=bigFM Charts
StationImage4			=bigFM.png
StationURL4				=http://streams.bigfm.de/bigfm-charts-128-aac?usid=0-0-H-A-D-30
StationTrackListURL4	=https://www.bigfm.de/playlist

StationTitle5			=bigFM Rock
StationImage5			=bigFM.png
StationURL5				=http://streams.bigfm.de/bigfm-rockamring-128-aac?usid=0-0-H-A-D-30
StationTrackListURL5	=https://www.bigfm.de/playlist

StationTitle6			=bigFM Worldbeats
StationImage6			=bigFM.png
StationURL6				=http://streams.bigfm.de/bigfm-worldbeats-128-aac?usid=0-0-H-A-D-30
StationTrackListURL6	=https://www.bigfm.de/playlist

StationTitle7			=Rock Antenne
StationImage7			=RockAntenne.png
StationURL7				=http://mp3channels.webradio.antenne.de:80/rockantenne
StationTrackListURL7	=http://www.webradio.de/antenne-bayern/rock-antenne

StationTitle8			=Technobase.FM
StationImage8			=TechnobaseFM.png
StationURL8				=http://listen.technobase.fm/tunein-dsl-pls
StationTrackListURL8	=https://www.technobase.fm/tracklist
