[LocationStyle]
FontColor=255,255,255
FontFace=Roboto
FontSize=11
StringAlign=LEFT
StringStyle=NORMAL
AntiAlias=1

[TempStyle]
FontColor=255,255,255
FontFace=Roboto Light
FontSize=35
StringAlign=LEFT
StringStyle=NORMAL
AntiAlias=1

[ForecastStyle]
FontColor=170,178,189
Fontface=Roboto
FontSize=9
StringCase=Upper
StringAlign=Center
StringStyle=NORMAL
AntiAlias=1

[LowsStyle]
FontColor=255,255,255
FontFace=Roboto
FontSize=9
StringAlign=LEFT
StringStyle=NORMAL
AntiAlias=1

[ImageRSSTitle]
FontColor=434a54
FontFace=Roboto Light
FontSize=12
StringAlign=LEFT
StringStyle=NORMAL
AntiAlias=1

[FeedContent]
H=16
W=247
X=r
Y=18r
FontColor=aab2bd
FontFace=Roboto
FontSize=9
StringAlign=LEFT
StringStyle=NORMAL
AntiAlias=1
ClipString=2

[Timeshadow]
FontColor=0,0,0,20
FontFace=Roboto Thin
FontSize=115
StringStyle=NORMAL
AntiAlias=1

[Time]
FontColor=255,255,255
FontFace=Roboto Thin
FontSize=115
StringStyle=NORMAL
AntiAlias=1

[DayText]
FontColor=3e454e
FontFace=Roboto Light
FontSize=17
StringStyle=NORMAL
AntiAlias=1

[DateText]
FontColor=a4acb6
FontFace=Roboto Light
FontSize=17
StringStyle=NORMAL
AntiAlias=1

[SideBarDateText]
FontColor=719c46
FontSize=7
StringAlign=LEFT
FontFace=AvantGarde LT Medium
AntiAlias=1